theme: jekyll-theme-minimal
title: V Chong-Morrison
logo: /assets/img/logo.jpg

collections:
  protocols:
    output: true
    permalink: /protocols/:path/
  mynotebook:
    output: true
    permalink: /mynotebook/:path/
    
plugins:
  - jekyll-seo-tag
  - jekyll-toc
